name: build

on: [ pull_request, push ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Maven
        run: sudo apt-get install maven

      - name: Make Gradle Wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | awk -F 'SimpleChemistryLib-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: SimpleChemistryLib ${{ steps.version.outputs.version }}
          path: build/libs/SimpleChemistryLib-${{ steps.version.outputs.version }}.jar

      - name: Get Mod Version
        id: mod_version
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | awk -F 'SimpleChemistryLib-1.20.1-|-|.jar' '{print $4}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Build Maven
        run: |
          mvn deploy:deploy-file -DgroupId=zh.qiushui.mods -DartifactId=SimpleChemistryLib -Dversion=${{ steps.mod_version.outputs.version }} -Dpackaging=jar -Dfile=build/libs/SimpleChemistryLib-${{ steps.version.outputs.version }}.jar -Durl=file:/mvn-repo/

      - name: Publish to target repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:QiuShui1012/maven.git
          BRANCH: snapshot
          FOLDER: mvn-repo/zh
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}